config/routes.rb
Bridge1::Application.routes.draw do
  resources :blog2s

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/blog2.rb
class Blog2 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog2s_controller.rb
class Blog2sController < ApplicationController
  # GET /blog2s
  # GET /blog2s.json
  def index
    @blog2s = Blog2.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog2s }
    end
  end

  # GET /blog2s/1
  # GET /blog2s/1.json
  def show
    @blog2 = Blog2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog2 }
    end
  end

  # GET /blog2s/new
  # GET /blog2s/new.json
  def new
    @blog2 = Blog2.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog2 }
    end
  end

  # GET /blog2s/1/edit
  def edit
    @blog2 = Blog2.find(params[:id])
  end

  # POST /blog2s
  # POST /blog2s.json
  def create
    @blog2 = Blog2.new(params[:blog2])

    respond_to do |format|
      if @blog2.save
        format.html { redirect_to @blog2, notice: 'Blog2 was successfully created.' }
        format.json { render json: @blog2, status: :created, location: @blog2 }
      else
        format.html { render action: "new" }
        format.json { render json: @blog2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog2s/1
  # PUT /blog2s/1.json
  def update
    @blog2 = Blog2.find(params[:id])

    respond_to do |format|
      if @blog2.update_attributes(params[:blog2])
        format.html { redirect_to @blog2, notice: 'Blog2 was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog2s/1
  # DELETE /blog2s/1.json
  def destroy
    @blog2 = Blog2.find(params[:id])
    @blog2.destroy

    respond_to do |format|
      format.html { redirect_to blog2s_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog2s_helper.rb
module Blog2sHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blog2s/_form.html.erb
<%= form_for(@blog2) do |f| %>
  <% if @blog2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog2.errors.count, "error") %> prohibited this blog2 from being saved:</h2>

      <ul>
      <% @blog2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog2s/edit.html.erb
<h1>Editing blog2</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog2 %> |
<%= link_to 'Back', blog2s_path %>

app/views/blog2s/index.html.erb
<h1>Listing blog2s</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog2s.each do |blog2| %>
  <tr>
    <td><%= blog2.title %></td>
    <td><%= blog2.body %></td>
    <td><%= link_to 'Show', blog2 %></td>
    <td><%= link_to 'Edit', edit_blog2_path(blog2) %></td>
    <td><%= link_to 'Destroy', blog2, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog2', new_blog2_path %>

app/views/blog2s/new.html.erb
<h1>New blog2</h1>

<%= render 'form' %>

<%= link_to 'Back', blog2s_path %>

app/views/blog2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog2.title %>
</p>

<p>
  <b>Body:</b>
  <%= @blog2.body %>
</p>


<%= link_to 'Edit', edit_blog2_path(@blog2) %> |
<%= link_to 'Back', blog2s_path %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.body %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Body:</b>
  <%= @blog.body %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bridge1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>